<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"><xsl:output method="xml" indent="yes" omit-xml-declaration="yes" encoding="UTF-8" /><!-- pass in params --><!--array holding references to constants, locals, lists ...--><xsl:param name="linkedListsArray" /><!-- calcsonly, calcsanddb --><xsl:param name="saveMethod" /><!-- default linked view --><xsl:param name="defaultLinkedViewId" /><!-- the last step is used to display different parts of the calculator--><xsl:param name="lastStepNumber" /><!-- what action is being taken by the server --><xsl:param name="serverActionType" /><!-- what other action is being taken by the server --><xsl:param name="serverSubActionType" /><!-- is the member viewing this uri the owner? --><xsl:param name="isURIOwningClub" /><!-- which node to start with? --><xsl:param name="nodeName" /><!-- which view to use? --><xsl:param name="viewEditType" /><!-- is this a coordinator? --><xsl:param name="memberRole" /><!-- what is the current uri? --><xsl:param name="selectedFileURIPattern" /><!-- the addin being used --><xsl:param name="calcDocURI" /><!-- the node being calculated (custom docs' nodename can be a devpack, while this might be budgetgroup) --><xsl:param name="docToCalcNodeName" /><!-- standard params used with calcs and custom docs --><xsl:param name="calcParams" /><!-- what is the name of the node to be selected? --><xsl:param name="selectionsNodeNeededName" /><!-- which network is this doc from? --><xsl:param name="networkId" /><!-- what is the start row? --><xsl:param name="startRow" /><!-- what is the end row? --><xsl:param name="endRow" /><!-- what are the pagination properties ? --><xsl:param name="pageParams" /><!-- what is the club's email? --><xsl:param name="clubEmail" /><!-- what is the current serviceid? --><xsl:param name="contenturipattern" /><!-- path to resources --><xsl:param name="fullFilePath" /><!-- init html --><xsl:template match="@*|/|node()" /><xsl:template match="/"><xsl:apply-templates select="root" /></xsl:template><xsl:template match="root"><div id="divAnalysisDoc"><h4 class="ui-bar-b">
			  Inputs Aggregate Analysis View
		  </h4><xsl:apply-templates select="inputgroup" /><div><a id="aFeedback" name="Feedback"><xsl:attribute name="href">mailto:<xsl:value-of select="$clubEmail" />?subject=<xsl:value-of select="$selectedFileURIPattern" /></xsl:attribute>
					Feedback About <xsl:value-of select="$selectedFileURIPattern" /></a></div></div></xsl:template><xsl:template match="inputgroup"><h4 class="ui-bar-b"><strong>Input Group or Type: <xsl:value-of select="@Name" /></strong></h4><xsl:apply-templates select="input" /></xsl:template><xsl:template match="input"><div data-role="collapsible" data-collapsed="false" data-theme="b" data-content-theme="d"><h4 class="ui-bar-b"><strong>Input Group or Input: <xsl:value-of select="@Name" /></strong></h4><div class="ui-grid-a"><div class="ui-block-a">
          Label: <xsl:value-of select="@Num" /></div><div class="ui-block-b">
          Observations: <xsl:value-of select="@Observations" /></div><div class="ui-block-a">
          OC Price; Mean; SD: <xsl:value-of select="@TOCPrice" />; <xsl:value-of select="@TOCPrice_MEAN" />; <xsl:value-of select="@TOCPrice_SD" /></div><div class="ui-block-b">
          OC Amount; Mean; SD: <xsl:value-of select="@TOCAmount" />; <xsl:value-of select="@TOCAmount_MEAN" />; <xsl:value-of select="@TOCAmount_SD" /></div><div class="ui-block-a">
          AOH Price; Mean; SD: <xsl:value-of select="@TAOHPrice" />; <xsl:value-of select="@TAOHPrice_MEAN" />; <xsl:value-of select="@TAOHPrice_SD" /></div><div class="ui-block-b">
          CAP Price; Mean; SD: <xsl:value-of select="@TCAPPrice" />; <xsl:value-of select="@TCAPPrice_MEAN" />; <xsl:value-of select="@TCAPPrice_SD" /></div></div><div><strong>Description : </strong><xsl:value-of select="@Description" /></div></div></xsl:template></xsl:stylesheet>