<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:DisplayComps="urn:displaycomps" version="1.0"><xsl:output method="xml" indent="yes" omit-xml-declaration="yes" encoding="UTF-8" /><!-- pass in params --><!--array holding references to constants, locals, lists ...--><xsl:param name="linkedListsArray" /><!-- calcsonly, calcsanddb --><xsl:param name="saveMethod" /><!-- default linked view --><xsl:param name="defaultLinkedViewId" /><!-- the last step is used to display different parts of the calculator--><xsl:param name="lastStepNumber" /><!-- what action is being taken by the server --><xsl:param name="serverActionType" /><!-- what other action is being taken by the server --><xsl:param name="serverSubActionType" /><!-- is the member viewing this uri the owner? --><xsl:param name="isURIOwningClub" /><!-- which node to start with? --><xsl:param name="nodeName" /><!-- which view to use? --><xsl:param name="viewEditType" /><!-- is this a coordinator? --><xsl:param name="memberRole" /><!-- what is the current uri? --><xsl:param name="selectedFileURIPattern" /><!-- the addin being used --><xsl:param name="calcDocURI" /><!-- the node being calculated (custom docs' nodename can be a devpack, while this might be budgetgroup) --><xsl:param name="docToCalcNodeName" /><!-- standard params used with calcs and custom docs --><xsl:param name="calcParams" /><!-- what is the name of the node to be selected? --><xsl:param name="selectionsNodeNeededName" /><!-- which network is this doc from? --><xsl:param name="networkId" /><!-- what is the start row? --><xsl:param name="startRow" /><!-- what is the end row? --><xsl:param name="endRow" /><!-- what are the pagination properties ? --><xsl:param name="pageParams" /><!-- what is the club's email? --><xsl:param name="clubEmail" /><!-- what is the current serviceid? --><xsl:param name="contenturipattern" /><!-- path to resources --><xsl:param name="fullFilePath" /><!-- init html --><xsl:template match="@*|/|node()" /><xsl:template match="/"><xsl:apply-templates select="root" /></xsl:template><xsl:template match="root"><div id="divAnalysisDoc"><h4 class="ui-bar-b">
			  Inputs Comparative Analysis View
		  </h4><xsl:apply-templates select="inputgroup" /><div><a id="aFeedback" name="Feedback"><xsl:attribute name="href">mailto:<xsl:value-of select="$clubEmail" />?subject=<xsl:value-of select="$selectedFileURIPattern" /></xsl:attribute>
						Feedback About <xsl:value-of select="$selectedFileURIPattern" /></a></div></div></xsl:template><xsl:template match="inputgroup"><h4 class="ui-bar-b">
      Input Group: <xsl:value-of select="@Name" /></h4><xsl:apply-templates select="input" /></xsl:template><xsl:template match="input"><xsl:variable name="fullcolcount" select="@Files" /><h4 class="ui-bar-b">
      Input: <xsl:value-of select="@Name" /></h4><div data-role="collapsible" data-theme="b" data-content-theme="d"><h4 class="ui-bar-b">
        Input Names
      </h4><div class="ui-grid-a"><xsl:value-of select="DisplayComps:WriteMobileNames(@Description, $fullcolcount)" /></div><h4 class="ui-bar-b">
        Total OC Prices: <xsl:value-of select="@TOCPrice" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TOCPrice_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Observations: <xsl:value-of select="@Observations" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:if test="starts-with($att_name, 'Observations_')"><xsl:value-of select="DisplayComps:printValue('Observations_', $att_name, $att_value )" /></xsl:if><xsl:if test="starts-with($att_name, 'TOCPrice_N1_')"><xsl:value-of select="DisplayComps:printValue('TOCPrice_N1_', $att_name, $att_value )" /></xsl:if></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Mean OC Prices: <xsl:value-of select="@TOCPrice_MEAN" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TOCPrice_MEAN_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Std. Dev. OC Prices: <xsl:value-of select="@TOCPrice_SD" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TOCPrice_SD_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Total OC Amounts: <xsl:value-of select="@TOCAmount" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TOCAmount_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Mean OC Amounts: <xsl:value-of select="@TOCAmount_MEAN" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TOCAmount_MEAN_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Std. Dev. OC Amounts: <xsl:value-of select="@TOCAmount_SD" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TOCAmount_SD_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Std. Dev. OC Amounts: <xsl:value-of select="@TOCAmount_SD" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TOCAmount_SD_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Total AOH Prices: <xsl:value-of select="@TAOHPrice" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TAOHPrice_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Mean AOH Prices: <xsl:value-of select="@TAOHPrice_MEAN" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TAOHPrice_MEAN_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Std. Dev. AOH Prices: <xsl:value-of select="@TAOHPrice_SD" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TAOHPrice_SD_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Total CAP Prices: <xsl:value-of select="@TCAPPrice" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TCAPPrice_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Mean CAP Prices: <xsl:value-of select="@TCAPPrice_MEAN" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TCAPPrice_MEAN_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><h4 class="ui-bar-b">
        Std. Dev. CAP Prices: <xsl:value-of select="@TCAPPrice_SD" /></h4><xsl:value-of select="DisplayComps:initValues($fullcolcount)" /><xsl:for-each select="@*"><xsl:variable name="att_name" select="name()" /><xsl:variable name="att_value" select="." /><xsl:value-of select="DisplayComps:printValue('TCAPPrice_SD_', $att_name, $att_value )" /></xsl:for-each><div class="ui-grid-a"><xsl:value-of select="DisplayComps:DoPrintMobileValues($fullcolcount)" /></div><div><strong>Description : </strong><xsl:value-of select="@Description" /></div></div></xsl:template></xsl:stylesheet>